class ContentLogSucessMessage(str):
    CONTENTLOG_CREATED = "Contenido correctamente creado."
    CONTENTLOG_GENERATED = "Contenido correctamente generado."
    CONTENTLOG_PROMPT_AUDITED = "Prompt auditado"
    CONTENTLOG_GET = "Contenido entregado correctamente."
    CONTENTLOGS_GET = "Contenidos listado correctamente"
    CONTENTLOG_DELETED = "Contenido correctamente eliminado."
    CONTENTLOG_UPDATED = "Contenido correctamente actualizado."
    CONTENTLOG_AUDITED = "Contenido correctamente auditado."
    CONTENTLOG_CREATED_AUDITED = "Contenido correctamente creado y auditado."
